import { ISLSignDefinition, ISLSign, SignAnchor } from '@/types/isl';

export const ISL_VOCABULARY: Record<ISLSign, ISLSignDefinition> = {
  // ==========================================
  // 1. EMERGENCY / NEEDS (10 Signs)
  // ==========================================
  HELP: {
    id: 'HELP',
    label: 'Help',
    category: 'emergency',
    description: 'Closed fist with thumb upright (A-shape) placed on or elevated above flat open palm.',
    motionType: 'static',
    instructions: [
      'Make a thumbs-up fist with dominant hand',
      'Place it over or tap upwards on flat non-dominant palm',
      'Hold steadily in front of chest',
    ],
    emoji: '🆘',
    keyPoints: ['Thumb extended upward', 'Other 4 fingers curled', 'Palm level or lifting upward'],
    speechText: 'I need help urgently',
    hindiTranslation: 'मुझे मदद चाहिए (Help)',
    twoHanded: true,
  },
  WATER: {
    id: 'WATER',
    label: 'Water',
    category: 'emergency',
    description: 'W-hand shape (index, middle, ring extended) tapped near chin or tilted toward mouth.',
    motionType: 'dynamic',
    instructions: [
      'Extend index, middle, and ring fingers apart forming "W"',
      'Curl thumb and pinky',
      'Tap index finger near corner of chin/mouth twice',
    ],
    emoji: '💧',
    keyPoints: ['3 fingers extended (Index, Middle, Ring)', 'Thumb & Pinky curled', 'Position near mouth/chin'],
    speechText: 'Please give me water',
    hindiTranslation: 'पानी (Water)',
    twoHanded: false,
  },
  FOOD: {
    id: 'FOOD',
    label: 'Food / Eat',
    category: 'emergency',
    description: 'All 5 fingertips bunched together (O-pinch / flat-O) tapping repeatedly toward mouth.',
    motionType: 'dynamic',
    instructions: [
      'Bring all fingertips and thumb together in a pinched bunch',
      'Point tips toward mouth',
      'Move hand towards mouth in tapping feeding motion',
    ],
    emoji: '🍲',
    keyPoints: ['Fingertips clustered together', 'Palm facing body/mouth', 'Forward/backward motion toward face'],
    speechText: 'I want food',
    hindiTranslation: 'खाना (Food)',
    twoHanded: false,
  },
  MEDICINE: {
    id: 'MEDICINE',
    label: 'Medicine',
    category: 'emergency',
    description: 'Middle finger extended downward rubbing in small circular motion against open flat palm.',
    motionType: 'dynamic',
    instructions: [
      'Hold non-dominant hand flat, palm facing up',
      'Extend middle finger of dominant hand while bending slightly',
      'Rub middle fingertip into center of flat palm like grinding medicine',
    ],
    emoji: '💊',
    keyPoints: ['Middle finger extended down', 'Flat non-dominant base palm', 'Circular palm grind contact'],
    speechText: 'I need medicine',
    hindiTranslation: 'दवा (Medicine)',
    twoHanded: true,
  },
  HOSPITAL: {
    id: 'HOSPITAL',
    label: 'Hospital',
    category: 'emergency',
    description: 'Index & middle fingers (H shape) draw a medical cross (+) on upper arm or chest.',
    motionType: 'dynamic',
    instructions: [
      'Extend index and middle fingers together',
      'Draw a vertical downward line on upper arm/shoulder',
      'Draw a horizontal crossing line forming a Red Cross symbol',
    ],
    emoji: '🏥',
    keyPoints: ['Index + Middle extended together (H-shape)', 'Two-stroke cross motion', 'Upper arm/shoulder region'],
    speechText: 'Take me to the hospital',
    hindiTranslation: 'अस्पताल (Hospital)',
    twoHanded: false,
  },
  POLICE: {
    id: 'POLICE',
    label: 'Police',
    category: 'emergency',
    description: 'C-hand shape or thumb & index finger placed over heart / opposite chest like a badge.',
    motionType: 'static',
    instructions: [
      'Curved index and thumb in a C-shape badge outline',
      'Tap or hold against left upper chest over heart',
      'Keep posture upright',
    ],
    emoji: '👮',
    keyPoints: ['C-shape curved thumb and index', 'Upper chest contact position', 'Remaining fingers slightly curled'],
    speechText: 'Call the police',
    hindiTranslation: 'पुलिस (Police)',
    twoHanded: false,
  },
  BATHROOM: {
    id: 'BATHROOM',
    label: 'Bathroom / Toilet',
    category: 'emergency',
    description: 'T-hand shape (fist with thumb poking between index and middle) shaking side-to-side.',
    motionType: 'dynamic',
    instructions: [
      'Make a fist with thumb tucked between index and middle finger (T-shape)',
      'Hold hand at chest height',
      'Shake wrist gently side to side',
    ],
    emoji: '🚻',
    keyPoints: ['T-shape thumb between knuckles', 'Horizontal side-to-side wrist shaking', 'Chest level height'],
    speechText: 'Where is the bathroom?',
    hindiTranslation: 'शौचालय (Bathroom)',
    twoHanded: false,
  },
  PAIN: {
    id: 'PAIN',
    label: 'Pain / Hurt',
    category: 'emergency',
    description: 'Both index fingers pointing towards each other, twisting inward repeatedly.',
    motionType: 'dynamic',
    instructions: [
      'Extend both index fingers, other fingers curled',
      'Point fingertips towards each other with slight gap',
      'Twist wrists in alternating counter-rotations',
    ],
    emoji: '🩹',
    keyPoints: ['Both index fingers extended', 'Fingertips facing', 'Twisting inward motion'],
    speechText: 'I am in pain',
    hindiTranslation: 'दर्द (Pain)',
    twoHanded: true,
  },
  DANGER: {
    id: 'DANGER',
    label: 'Danger / Emergency',
    category: 'emergency',
    description: 'Both arms crossed at wrists forming an X-barrier in front of chest.',
    motionType: 'static',
    instructions: [
      'Form closed fists or flat palms with both hands',
      'Cross wrists across chest forming an "X"',
      'Hold firmly with firm posture',
    ],
    emoji: '⚠️',
    keyPoints: ['Both wrists crossed in front of chest', 'X-formation', 'High visibility emergency posture'],
    speechText: 'Warning, danger ahead',
    hindiTranslation: 'खतरा (Danger)',
    twoHanded: true,
  },
  AMBULANCE: {
    id: 'AMBULANCE',
    label: 'Ambulance',
    category: 'emergency',
    description: 'Open hand rotated above head simulating a flashing emergency beacon light.',
    motionType: 'dynamic',
    instructions: [
      'Raise dominant hand near or above head level',
      'Open and close palm or rotate wrist circularly',
      'Mimic rotating flashing beacon',
    ],
    emoji: '🚑',
    keyPoints: ['High hand position above shoulder', 'Rotational or pulsating palm flashing', 'Emergency cue'],
    speechText: 'Call an ambulance',
    hindiTranslation: 'एम्बुलेंस (Ambulance)',
    twoHanded: false,
  },

  // ==========================================
  // 2. CAMPUS / ACTION / ACADEMIC (12 Signs)
  // ==========================================
  TEACHER: {
    id: 'TEACHER',
    label: 'Teacher',
    category: 'campus',
    description: 'Both hands in flattened-O shapes near temples moving forward in giving knowledge.',
    motionType: 'dynamic',
    instructions: [
      'Place both hands near temples with fingers curved',
      'Move both hands outward and forward away from head',
      'Drop hands down into open agent marker',
    ],
    emoji: '🧑‍🏫',
    keyPoints: ['Two hands near head level', 'Forward knowledge-sharing vector', 'Parallel movement'],
    speechText: 'Teacher',
    hindiTranslation: 'शिक्षक / अध्यापक (Teacher)',
    twoHanded: true,
  },
  CLASS: {
    id: 'CLASS',
    label: 'Class / Classroom',
    category: 'campus',
    description: 'Both hands in C-shapes starting touching at index fingers and drawing an outward circle.',
    motionType: 'dynamic',
    instructions: [
      'Form "C" shapes with both hands',
      'Touch thumbs and index fingers together in front',
      'Move hands outward in a sweeping circle until pinkies touch',
    ],
    emoji: '🏫',
    keyPoints: ['Both hands in C-shape', 'Outward circular sweep', 'Enclosing classroom circle'],
    speechText: 'Classroom',
    hindiTranslation: 'कक्षा (Class)',
    twoHanded: true,
  },
  GO: {
    id: 'GO',
    label: 'Go',
    category: 'campus',
    description: 'Both index fingers pointing forward and arcing away from the body.',
    motionType: 'dynamic',
    instructions: [
      'Point both index fingers upwards/forward',
      'Swing wrists in an outward arc forward away from body',
      'Crisp decisive movement',
    ],
    emoji: '🏃',
    keyPoints: ['Index fingers extended', 'Forward throwing arc vector', 'Directional movement away'],
    speechText: 'Please go',
    hindiTranslation: 'जाओ (Go)',
    twoHanded: false,
  },
  COME: {
    id: 'COME',
    label: 'Come',
    category: 'campus',
    description: 'Index fingers or open hands curling inwards towards chest beckoning.',
    motionType: 'dynamic',
    instructions: [
      'Hold hands extended outward at chest height',
      'Beckon inward with palms facing yourself',
      'Pull hands towards chest',
    ],
    emoji: '👋',
    keyPoints: ['Inward motion vector toward torso', 'Palms facing user', 'Beckoning curl'],
    speechText: 'Please come here',
    hindiTranslation: 'आओ (Come)',
    twoHanded: false,
  },
  STOP: {
    id: 'STOP',
    label: 'Stop',
    category: 'campus',
    description: 'Dominant hand with flat rigid vertical palm chopping down firmly into open horizontal palm.',
    motionType: 'static',
    instructions: [
      'Hold non-dominant hand flat horizontally with palm up',
      'Bring dominant hand with flat vertical edge chopping down into center of palm',
      'Halt decisively',
    ],
    emoji: '🛑',
    keyPoints: ['Flat vertical cutting hand', 'Flat horizontal receiving palm', 'Sharp stopping posture'],
    speechText: 'Stop now',
    hindiTranslation: 'रुकें (Stop)',
    twoHanded: true,
  },
  WAIT: {
    id: 'WAIT',
    label: 'Wait',
    category: 'campus',
    description: 'Both hands held forward with palms angled down/forward, gently undulating fingers.',
    motionType: 'dynamic',
    instructions: [
      'Hold both open hands in front of body at waist/chest height',
      'Palms angled slightly up and facing inward/forward',
      'Wiggle fingers gently while holding position',
    ],
    emoji: '⏳',
    keyPoints: ['Open palms spread', 'Finger flutter / gentle hold', 'Chest level forward position'],
    speechText: 'Please wait a moment',
    hindiTranslation: 'प्रतीक्षा करें (Wait)',
    twoHanded: true,
  },
  REPEAT: {
    id: 'REPEAT',
    label: 'Repeat / Again',
    category: 'campus',
    description: 'Dominant curved right hand flipping up and landing flat into the open left palm.',
    motionType: 'dynamic',
    instructions: [
      'Hold non-dominant palm flat facing up/right',
      'Bend dominant hand at knuckles and arc in a curved loop',
      'Land fingertips firmly into open palm center',
    ],
    emoji: '🔁',
    keyPoints: ['Curved arcing motion', 'Landing in palm target', 'Repetition gesture'],
    speechText: 'Please repeat again',
    hindiTranslation: 'दोहराएं (Repeat)',
    twoHanded: true,
  },
  WANT: {
    id: 'WANT',
    label: 'Want',
    category: 'campus',
    description: 'Both hands open with palms facing up, curving into claw-like shapes while pulling towards chest.',
    motionType: 'dynamic',
    instructions: [
      'Hold both hands forward with palms facing upward',
      'Curl fingers slightly into loose claw hooks',
      'Pull both hands back towards your torso',
    ],
    emoji: '🤲',
    keyPoints: ['Palms facing up', 'Fingers curving to claws', 'Inward pull motion vector'],
    speechText: 'I want this',
    hindiTranslation: 'चाहिए (Want)',
    twoHanded: true,
  },
  NEED: {
    id: 'NEED',
    label: 'Need / Must',
    category: 'campus',
    description: 'Dominant hand index finger hooked in X-shape, bending downward forcefully.',
    motionType: 'dynamic',
    instructions: [
      'Bend index finger into a hooked "X" shape with thumb tucked',
      'Drop wrist downwards forcefully at wrist joint',
      'Repeat downward bending pump',
    ],
    emoji: '❗',
    keyPoints: ['Hooked X-index finger', 'Downward wrist flex', 'Authoritative downward vector'],
    speechText: 'I need this urgently',
    hindiTranslation: 'आवश्यकता है (Need)',
    twoHanded: false,
  },
  LEARN: {
    id: 'LEARN',
    label: 'Learn / Study',
    category: 'campus',
    description: 'Taking knowledge from open flat palm (book) and closing fingers onto forehead.',
    motionType: 'dynamic',
    instructions: [
      'Hold non-dominant hand flat like an open book',
      'Place dominant fingertips flat on the open palm',
      'Lift dominant fingertips up and bring together to touch forehead',
    ],
    emoji: '📖',
    keyPoints: ['Palm to forehead trajectory', 'Fingertips gathering knowledge', 'Two-handed coordination'],
    speechText: 'I am learning',
    hindiTranslation: 'सीखना (Learn)',
    twoHanded: true,
  },
  BOOK: {
    id: 'BOOK',
    label: 'Book',
    category: 'campus',
    description: 'Both flat palms joined together at palms, then opening outward hinged at pinkies like a book.',
    motionType: 'dynamic',
    instructions: [
      'Place both flat hands together palm-to-palm',
      'Open palms outward keeping pinky edges touching',
      'Form an open book shape facing upward',
    ],
    emoji: '📚',
    keyPoints: ['Two flat hands', 'Hinged at pinky edges', 'Opening outward book posture'],
    speechText: 'Book',
    hindiTranslation: 'किताब (Book)',
    twoHanded: true,
  },
  WRITE: {
    id: 'WRITE',
    label: 'Write / Notes',
    category: 'campus',
    description: 'Dominant hand thumb and index pinching an imaginary pen, scribbling across flat open non-dominant palm.',
    motionType: 'dynamic',
    instructions: [
      'Hold non-dominant palm flat facing up (paper)',
      'Pinch dominant thumb and index together holding invisible pen',
      'Glide fingertip across flat palm in rapid writing strokes',
    ],
    emoji: '✍️',
    keyPoints: ['Pen pinch grip', 'Writing glide across base palm', 'Side-to-side stroke motion'],
    speechText: 'Please write it down',
    hindiTranslation: 'लिखना (Write)',
    twoHanded: true,
  },

  PEACE: {
    id: 'PEACE',
    label: 'Peace / Two',
    category: 'campus',
    description: 'Index and middle fingers extended upright spread apart forming a "V" (Peace sign), other fingers folded.',
    motionType: 'static',
    instructions: [
      'Extend index and middle fingers upward in a V-shape',
      'Fold ring and pinky fingers flat to palm held by thumb',
      'Hold steadily facing forward at chest level',
    ],
    emoji: '✌️',
    keyPoints: ['Index & Middle extended', 'Thumb holding Ring & Pinky', 'V-shape spread'],
    speechText: 'Peace',
    hindiTranslation: 'शांति / दो (Peace)',
    twoHanded: false,
  },

  // ==========================================
  // 3. GREETINGS / COURTESY (10 Signs)
  // ==========================================
  HELLO: {
    id: 'HELLO',
    label: 'Hello',
    category: 'greetings',
    description: 'Open flat hand with thumb tucked or extended, starting near temple and saluting outward with a gentle wave.',
    motionType: 'dynamic',
    instructions: [
      'Hold flat open hand with palm facing outward near temple/forehead',
      'Move hand outward and slightly upward in a friendly salute',
      'Smile and maintain eye contact',
    ],
    emoji: '👋',
    keyPoints: ['All 4 fingers extended flat', 'Palm facing forward/outward', 'Head-height salute motion'],
    speechText: 'Hello, greetings!',
    hindiTranslation: 'नमस्ते / हैलो (Hello)',
    twoHanded: false,
  },
  GOODBYE: {
    id: 'GOODBYE',
    label: 'Goodbye',
    category: 'greetings',
    description: 'Open hand held up waving fingers or opening/closing palm repeatedly side to side.',
    motionType: 'dynamic',
    instructions: [
      'Raise open hand at shoulder height, palm facing forward',
      'Wave entire hand side to side or open and close all fingers',
      'Keep arm relaxed and visible',
    ],
    emoji: '🙋',
    keyPoints: ['Open palm facing camera', 'Lateral side-to-side oscillation', 'High frame variance in X coordinate'],
    speechText: 'Goodbye, have a good day',
    hindiTranslation: 'अलविदा (Goodbye)',
    twoHanded: false,
  },
  THANK_YOU: {
    id: 'THANK_YOU',
    label: 'Thank You',
    category: 'greetings',
    description: 'Flat open hand touching fingertips to chin/lips and extending outward forward with palm facing up.',
    motionType: 'dynamic',
    instructions: [
      'Touch fingertips of open flat hand to chin or lower lip',
      'Move hand straight forward and slightly downward towards listener',
      'End with palm facing slightly upward',
    ],
    emoji: '🙏',
    keyPoints: ['Fingertips touching chin/mouth', 'Forward extending vector', 'Flat open palm'],
    speechText: 'Thank you very much',
    hindiTranslation: 'धन्यवाद (Thank You)',
    twoHanded: false,
  },
  PLEASE: {
    id: 'PLEASE',
    label: 'Please',
    category: 'greetings',
    description: 'Flat open hand with fingers together, rubbing in a smooth circular clockwise motion over center of chest.',
    motionType: 'dynamic',
    instructions: [
      'Place open flat hand on center of upper chest',
      'Keep fingers straight and thumb aligned',
      'Rub hand in clockwise circular cycles over chest',
    ],
    emoji: '🥺',
    keyPoints: ['Flat palm on chest', 'Circular 2D orbital trajectory', 'Chest level anchor'],
    speechText: 'Please',
    hindiTranslation: 'कृपया (Please)',
    twoHanded: false,
  },
  SORRY: {
    id: 'SORRY',
    label: 'Sorry',
    category: 'greetings',
    description: 'Closed fist (A-shape) rubbing in circular motion on center of chest.',
    motionType: 'dynamic',
    instructions: [
      'Make a closed fist with thumb over fingers (A-hand shape)',
      'Place knuckles against center of chest',
      'Rub in small circular rotations',
    ],
    emoji: '🙏',
    keyPoints: ['Closed fist (all fingers curled)', 'Chest center contact', 'Circular rubbing trajectory'],
    speechText: 'I am really sorry',
    hindiTranslation: 'माफ़ कीजिए (Sorry)',
    twoHanded: false,
  },
  YES: {
    id: 'YES',
    label: 'Yes',
    category: 'greetings',
    description: 'Closed fist (S-shape) tilting / nodding up and down from the wrist like a nodding head.',
    motionType: 'dynamic',
    instructions: [
      'Make a closed fist held at chest/shoulder height',
      'Tilt wrist up and down repeatedly like a nodding head',
      'Keep arm steady and isolate wrist flex',
    ],
    emoji: '👍',
    keyPoints: ['Closed fist shape', 'Vertical pitch oscillation in Y/Z', 'Nodding cycle'],
    speechText: 'Yes, definitely',
    hindiTranslation: 'हाँ (Yes)',
    twoHanded: false,
  },
  NO: {
    id: 'NO',
    label: 'No',
    category: 'greetings',
    description: 'Index and middle fingers extended straight, snapping down to tap the thumb firmly like a beak.',
    motionType: 'dynamic',
    instructions: [
      'Extend index and middle finger together with thumb opposed',
      'Snap index and middle fingertips down onto thumb pad',
      'Quick decisive clamping closure',
    ],
    emoji: '🙅',
    keyPoints: ['Index & Middle extended then pinched to thumb', 'Ring and Pinky curled', 'Snap closure'],
    speechText: 'No',
    hindiTranslation: 'नहीं (No)',
    twoHanded: false,
  },
  OKAY: {
    id: 'OKAY',
    label: 'Okay / Perfect',
    category: 'greetings',
    description: 'Thumb and index finger touching tips forming a circle ("O"), with middle, ring, and pinky extended upward.',
    motionType: 'static',
    instructions: [
      'Join tips of thumb and index finger forming a circle',
      'Extend middle, ring, and pinky fingers upright and spread',
      'Hold steadily in front of chest facing forward',
    ],
    emoji: '👌',
    keyPoints: ['Thumb-Index contact pinch', 'Middle, Ring, Pinky extended', 'Palm facing camera'],
    speechText: 'Everything is okay',
    hindiTranslation: 'ठीक है (Okay)',
    twoHanded: false,
  },
  NAMASTE: {
    id: 'NAMASTE',
    label: 'Namaste / Welcome',
    category: 'greetings',
    description: 'Both flat hands pressed together palm-to-palm at chest level in prayer pose (Anjali Mudra).',
    motionType: 'static',
    instructions: [
      'Join both palms together flat in front of chest center',
      'Fingers pointing vertically upwards',
      'Hold steadily with elbows relaxed',
    ],
    emoji: '🙏',
    keyPoints: ['Both palms pressed together', 'Fingers pointing straight up', 'Centered in front of chest'],
    speechText: 'Namaste, welcome',
    hindiTranslation: 'नमस्ते (Namaste)',
    twoHanded: true,
  },
  FRIEND: {
    id: 'FRIEND',
    label: 'Friend',
    category: 'greetings',
    description: 'Both index fingers hooked together in an interlocking handshake, then flipped and hooked the other way.',
    motionType: 'static',
    instructions: [
      'Extend both index fingers curved like hooks',
      'Hook right index finger over left index finger',
      'Hold closely together at chest level',
    ],
    emoji: '🤝',
    keyPoints: ['Both index fingers hooked', 'Close proximity contact', 'Chest height'],
    speechText: 'You are my friend',
    hindiTranslation: 'दोस्त / मित्र (Friend)',
    twoHanded: true,
  },
  STUDENT: {
    id: 'STUDENT',
    label: 'Student',
    category: 'campus',
    description: 'Learn sign from palm combined with agent person marker downward.',
    motionType: 'dynamic',
    instructions: ['Take knowledge from open flat palm to forehead', 'Bring hands down in parallel student marker'],
    emoji: '🎓',
    keyPoints: ['Two hands present', 'Chest / head coordination'],
    speechText: 'Student',
    hindiTranslation: 'छात्र (Student)',
    twoHanded: true,
  },
  DESK: {
    id: 'DESK',
    label: 'Desk / Table',
    category: 'campus',
    description: 'Both forearms held horizontal resting across each other outlining a desk surface.',
    motionType: 'static',
    instructions: ['Place one forearm horizontally across chest', 'Rest other forearm gently on top parallel'],
    emoji: '🏢',
    keyPoints: ['Dual horizontal forearms', 'Desk plane marker'],
    speechText: 'Helpdesk',
    hindiTranslation: 'सहायता डेस्क (Helpdesk)',
    twoHanded: true,
  },
  WHERE: {
    id: 'WHERE',
    label: 'Where',
    category: 'campus',
    description: 'Index finger pointing upward oscillating gently side to side seeking location.',
    motionType: 'dynamic',
    instructions: ['Point index finger straight up', 'Pivot wrist gently side to side'],
    emoji: '📍',
    keyPoints: ['Index point upright', 'Lateral oscillation'],
    speechText: 'Where',
    hindiTranslation: 'कहाँ (Where)',
    twoHanded: false,
  },
  IDLE: {
    id: 'IDLE',
    label: 'Idle / Neutral',
    category: 'greetings',
    description: 'Hands in neutral resting position.',
    motionType: 'static',
    instructions: ['Rest hands naturally'],
    emoji: '✋',
    keyPoints: ['Neutral position'],
    speechText: '',
    hindiTranslation: 'निष्क्रिय (Idle)',
    twoHanded: false,
  },
};

export const ISL_SIGNS_LIST = Object.values(ISL_VOCABULARY).filter((s) => s.id !== 'IDLE');

/**
 * Default Orthonormal Feature Anchors for Cosine Similarity Matching
 */
export const DEFAULT_ANCHORS: Record<string, SignAnchor> = {
  HELP: {
    sign: 'HELP',
    vector63: [0,0,0, -0.22,0.35,-0.05, -0.42,0.65,-0.12, -0.55,0.92,-0.18, -0.62,1.15,-0.22, 0,1,0, -0.05,0.72,-0.25, -0.08,0.52,-0.32, -0.09,0.38,-0.35, 0.28,0.95,-0.02, 0.22,0.68,-0.28, 0.18,0.48,-0.34, 0.15,0.35,-0.36, 0.52,0.85,-0.05, 0.44,0.60,-0.28, 0.38,0.42,-0.34, 0.34,0.30,-0.36, 0.72,0.72,-0.08, 0.62,0.48,-0.25, 0.54,0.35,-0.30, 0.48,0.25,-0.32],
    twoHanded: true,
    relativeDistance: 0.22,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  WATER: {
    sign: 'WATER',
    vector63: [0,0,0, -0.25,0.32,-0.08, -0.38,0.52,-0.15, -0.42,0.65,-0.20, -0.44,0.72,-0.22, 0,1,0, -0.02,1.38,-0.02, -0.03,1.72,-0.03, -0.04,2.05,-0.04, 0.28,0.95,-0.02, 0.32,1.35,-0.03, 0.35,1.70,-0.04, 0.38,2.02,-0.05, 0.52,0.85,-0.05, 0.58,1.22,-0.06, 0.62,1.55,-0.07, 0.65,1.85,-0.08, 0.72,0.72,-0.08, 0.62,0.48,-0.25, 0.54,0.35,-0.30, 0.48,0.25,-0.32],
    twoHanded: false,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  FOOD: {
    sign: 'FOOD',
    vector63: [0,0,0, -0.15,0.35,-0.08, -0.22,0.62,-0.15, -0.18,0.85,-0.22, -0.08,1.05,-0.28, 0,1,0, 0.02,1.15,-0.15, 0.03,1.18,-0.28, 0.02,1.12,-0.35, 0.22,0.95,-0.02, 0.18,1.12,-0.16, 0.14,1.15,-0.28, 0.10,1.10,-0.36, 0.42,0.85,-0.05, 0.34,1.02,-0.18, 0.26,1.06,-0.29, 0.18,1.04,-0.36, 0.62,0.72,-0.08, 0.48,0.88,-0.20, 0.36,0.95,-0.30, 0.24,0.96,-0.37],
    twoHanded: false,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  OKAY: {
    sign: 'OKAY',
    vector63: [0,0,0, -0.18,0.32,-0.05, -0.28,0.58,-0.12, -0.22,0.82,-0.18, -0.12,0.98,-0.22, 0,1,0, 0.02,1.08,-0.10, 0.01,1.05,-0.20, -0.05,0.98,-0.24, 0.28,0.95,-0.02, 0.35,1.38,-0.03, 0.40,1.75,-0.04, 0.44,2.10,-0.05, 0.52,0.85,-0.05, 0.60,1.25,-0.06, 0.66,1.60,-0.07, 0.70,1.92,-0.08, 0.72,0.72,-0.08, 0.80,1.08,-0.09, 0.86,1.40,-0.10, 0.90,1.70,-0.11],
    twoHanded: false,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  STOP: {
    sign: 'STOP',
    vector63: [0,0,0, -0.28,0.35,-0.02, -0.48,0.65,-0.05, -0.58,0.90,-0.08, -0.65,1.12,-0.10, 0,1,0, 0.02,1.40,0.02, 0.03,1.78,0.03, 0.04,2.12,0.04, 0.28,0.95,-0.01, 0.32,1.40,-0.01, 0.35,1.80,-0.01, 0.38,2.18,-0.01, 0.52,0.85,-0.03, 0.58,1.28,-0.03, 0.62,1.68,-0.03, 0.65,2.02,-0.03, 0.72,0.72,-0.05, 0.80,1.12,-0.05, 0.86,1.48,-0.05, 0.90,1.80,-0.05],
    twoHanded: true,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  HELLO: {
    sign: 'HELLO',
    vector63: [0,0,0, -0.25,0.35,-0.02, -0.45,0.65,-0.05, -0.55,0.90,-0.08, -0.62,1.12,-0.10, 0,1,0, 0.02,1.40,0.02, 0.03,1.78,0.03, 0.04,2.12,0.04, 0.28,0.95,-0.01, 0.32,1.40,-0.01, 0.35,1.80,-0.01, 0.38,2.18,-0.01, 0.52,0.85,-0.03, 0.58,1.28,-0.03, 0.62,1.68,-0.03, 0.65,2.02,-0.03, 0.72,0.72,-0.05, 0.80,1.12,-0.05, 0.86,1.48,-0.05, 0.90,1.80,-0.05],
    twoHanded: false,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  NAMASTE: {
    sign: 'NAMASTE',
    vector63: [0,0,0, -0.22,0.35,-0.02, -0.42,0.65,-0.05, -0.52,0.90,-0.08, -0.58,1.12,-0.10, 0,1,0, 0.02,1.40,0.02, 0.03,1.78,0.03, 0.04,2.12,0.04, 0.28,0.95,-0.01, 0.32,1.40,-0.01, 0.35,1.80,-0.01, 0.38,2.18,-0.01, 0.52,0.85,-0.03, 0.58,1.28,-0.03, 0.62,1.68,-0.03, 0.65,2.02,-0.03, 0.72,0.72,-0.05, 0.80,1.12,-0.05, 0.86,1.48,-0.05, 0.90,1.80,-0.05],
    twoHanded: true,
    relativeDistance: 0.12,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  POLICE: {
    sign: 'POLICE',
    vector63: [0,0,0, -0.22,0.32,-0.08, -0.38,0.58,-0.15, -0.32,0.82,-0.22, -0.15,0.95,-0.26, 0,1,0, 0.05,1.28,-0.12, 0.04,1.42,-0.28, -0.08,1.38,-0.42, 0.28,0.95,-0.02, 0.28,1.22,-0.14, 0.22,1.35,-0.29, 0.10,1.32,-0.44, 0.52,0.85,-0.05, 0.48,1.10,-0.16, 0.38,1.22,-0.30, 0.25,1.20,-0.45, 0.72,0.72,-0.08, 0.64,0.95,-0.18, 0.52,1.05,-0.32, 0.38,1.04,-0.46],
    twoHanded: false,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  MEDICINE: {
    sign: 'MEDICINE',
    vector63: [0,0,0, -0.22,0.35,-0.05, -0.42,0.65,-0.12, -0.48,0.82,-0.20, -0.45,0.95,-0.25, 0,1,0, -0.05,0.72,-0.25, -0.08,0.52,-0.32, -0.09,0.38,-0.35, 0.28,0.95,-0.02, 0.32,1.38,-0.03, 0.35,1.75,-0.04, 0.38,2.05,-0.05, 0.52,0.85,-0.05, 0.44,0.60,-0.28, 0.38,0.42,-0.34, 0.34,0.30,-0.36, 0.72,0.72,-0.08, 0.62,0.48,-0.25, 0.54,0.35,-0.30, 0.48,0.25,-0.32],
    twoHanded: true,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
  HOSPITAL: {
    sign: 'HOSPITAL',
    vector63: [0,0,0, -0.25,0.32,-0.08, -0.40,0.55,-0.18, -0.44,0.70,-0.24, -0.45,0.82,-0.28, 0,1,0, -0.02,1.38,-0.02, -0.03,1.75,-0.03, -0.04,2.08,-0.04, 0.28,0.95,-0.02, 0.28,1.35,-0.03, 0.28,1.72,-0.04, 0.28,2.05,-0.05, 0.52,0.85,-0.05, 0.44,0.60,-0.28, 0.38,0.42,-0.34, 0.34,0.30,-0.36, 0.72,0.72,-0.08, 0.62,0.48,-0.25, 0.54,0.35,-0.30, 0.48,0.25,-0.32],
    twoHanded: false,
    sampleCount: 100,
    lastUpdated: Date.now(),
  },
};

/**
 * Dynamic In-Memory Anchor Registry
 */
class DynamicAnchorRegistry {
  private anchors: Record<string, SignAnchor> = { ...DEFAULT_ANCHORS };

  public getAnchor(sign: string): SignAnchor | undefined {
    return this.anchors[sign];
  }

  public getAllAnchors(): Record<string, SignAnchor> {
    return { ...this.anchors };
  }

  public updateAnchor(anchor: SignAnchor): void {
    this.anchors[anchor.sign] = anchor;
  }

  public loadAnchors(anchors: Record<string, SignAnchor>): void {
    this.anchors = { ...this.anchors, ...anchors };
  }

  public resetToDefaults(): void {
    this.anchors = { ...DEFAULT_ANCHORS };
  }
}

export const anchorRegistry = new DynamicAnchorRegistry();
